dist: trusty
sudo: false
language: cpp
compiler: clang

matrix:
  include:
    - os: linux
      addons:
        apt:
          packages:
            - libc++-dev
            - libc++-helpers
            - libc++1
            - clang-3.5
            - cmake
            - libboost-all-dev
      env:
        - MATRIX_EVAL="CC=clang-3.5 && CXX=clang++-3.5"

script:
  - mkdir build
  - cd build
  - cmake .. -DBUILD_SSL=YES -DCMAKE_BUILD_TYPE=Debug
  - make -j4
